### ISSUE TITLE
Install failed due to unknown export

### ISSUE THREAD

**Issue by ananth1996** [rOpenGov/bibliographica#22]
Hi, on trying to install this package I got the following error. 
```
Error: package or namespace load failed for ‘bibliographica’ in namespaceExport(ns, exports):
 undefined exports: validate_publication_time
Error: loading failed
Execution halted
```
Upon checking the repository, this [commit](https://github.com/COMHIS/bibliographica/commit/c6ac0690679dc453fdf032c45e6ac9d578fda493) causes the issue as `validate_publication_time` is present in NAMESPACE but the code has been removed. 

I verified that installing the previous commit via 
```
install_github("ropengov/bibliographica@470fe313851ca1e0650ee1715e3e73b2b1a2efb5")
```
works as intended.

**Comment by antagomir** [comment]
Hi! The maintenance of this package is currently not active as the harmonization functions are rather specific to data set, and the package needs redesign and scoping. We have improved versions of most functionalities in dataset-specific repos.
