### ISSUE TITLE
Bibliographica failing to install 

### ISSUE THREAD

**Issue by jamielatham15** [rOpenGov/bibliographica#3]
Hi there,

I am having trouble installing the Bibliographica package to R version 3.2.3

I have tried several things, including rolling back my R version, but it nonetheless throws the following error message:

```
> install_github("rOpengov/bibliographica")
Downloading GitHub repo rOpengov/bibliographica@master
from URL https://api.github.com/repos/rOpengov/bibliographica/zipball/master
Installing bibliographica
Skipping 1 unavailable package: genderdata
"C:/PROGRA~1/R/R-32~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD  \
  INSTALL  \
  "C:/Users/*****/AppData/Local/Temp/RtmpO6v03Q/devtools91843f342ed/rOpenGov-bibliographica-9af72be"  \
  --library="C:/Users/******/Documents/R/win-library/3.2" --install-tests 

* installing *source* package 'bibliographica' ...
** R
** inst
** tests
** preparing package for lazy loading
Error : object 'condense_spaces' is not exported by 'namespace:sorvi'
ERROR: lazy loading failed for package 'bibliographica'
* removing 'C:/Users/******/Documents/R/win-library/3.2/bibliographica'
Error: Command failed (1)
```

Any ideas? I managed to use this package successfully about 6 months ago, but I reinstalled my OS  and since then it hasn't worked.

I am running Windows 10, Rstudio 0.99.876 and R 3.2.3

Many thanks,

Jamie

**Comment by antagomir** [comment]
You should probably install sorvi development version (condense_spaces is not in the CRAN release version yet): use install_github("ropengov/sorvi")

Note that the whole bibliographica package is in heavy development stage and still very unstable - many functions can change.

**Comment by jamielatham15** [comment]
worked perfectly thank you. This is a very useful package for my PhD work with ESTC data. I will bear in mind that it is still under development though.

Thanks again! Ill be sure to cite your package properly

**Comment by antagomir** [comment]
Thanks. Please cite the R package and A Quantitative Study of History in the English Short-Title Catalogue (ESTC) 1470-1800 Leo Lahti, Niko Ilomäki, Mikko Tolonen. LIBER Quarterly 25(2):87-116, 2015 https://www.liberquarterly.eu/articles/10.18352/lq.10112/ 

Also any feedback, suggestions for improvement, or bug fixes are welcome. Things are still moving with this package as I said so do not expect perfect stability for a while.
